"""Response schemas for the frontend-bound endpoints.

⭐ ATTACHED WITH `responses={200: {"model": X}}`, NEVER `response_model=X`, AND
THE DIFFERENCE IS A PRODUCTION INCIDENT. `response_model` FILTERS the response to
the model's declared fields — verified: a handler returning {"a": 1, "b": "..."}
under a model declaring only `a` returns {"a": 1}, and `b` is gone. Silently. On
payloads this size, assembled across many modules, any field the model failed to
enumerate would vanish from the API with nothing raised and nothing logged.

Both forms produce an identical `$ref` in the OpenAPI document, so the frontend
gets exactly the same generated types either way. One of them can delete customer
data from a response and the other cannot.

⭐ AND THE MODELS ARE INFERRED FROM LIVE PAYLOADS, NOT FROM READING THE HANDLERS.
A hand-written model is a second description of the response that drifts from the
first; these were generated by calling the deployed endpoints and reading what
they actually return. Every field is Optional because the shape genuinely varies
(honest-empty states, k-floored slices, absent datasets) — a required field here
would be a claim the payload does not make.

Nested objects are `dict[str, Any]` deliberately: typing them from one sample
would encode that sample's optional keys as the contract. The top level is what
the frontend binds to and what removes the `any` at the call site.
"""
from typing import Any

from pydantic import BaseModel


class AssessmentSummaryOut(BaseModel):
    revision: int | None = None
    current_cycle_id: int | None = None
    current_cycle_closed: bool | None = None
    current_cycle_depth: str | None = None
    current_cycle_name: str | None = None
    cycle_count: int | None = None
    cei: float | None = None
    n_participants: int | None = None
    n_respondents: int | None = None
    suppression: Any | None = None
    l1_subscores: list[dict[str, Any]] | None = None
    radar: list[dict[str, Any]] | None = None
    item_dispersion: dict[str, Any] | None = None
    departments: dict[str, Any] | None = None
    seniorities: dict[str, Any] | None = None
    cross: dict[str, Any] | None = None
    department_filter: Any | None = None
    department_slice: Any | None = None
    seniority_filter: Any | None = None
    seniority_slice: Any | None = None
    intersection_slice: Any | None = None
    abstention_rates: dict[str, Any] | None = None
    no_signal_items: list[Any] | None = None
    item_rag: dict[str, Any] | None = None
    l1_rag: dict[str, Any] | None = None
    sentiment_available: bool | None = None
    trend: list[dict[str, Any]] | None = None
    cadence: dict[str, Any] | None = None


class AssessmentCurrentOut(BaseModel):
    company_id: int | None = None
    open_cycle: Any | None = None
    invited: int | None = None
    responded: int | None = None


class DatasetOut(BaseModel):
    id: int | None = None
    name: str | None = None
    standard: str | None = None
    ownership: str | None = None
    source: str | None = None
    enterprise_id: int | None = None
    version: int | None = None
    is_active: bool | None = None
    validation: dict[str, Any] | None = None
    created_at: str | None = None
    data: dict[str, Any] | None = None


class InitiativeListOut(BaseModel):
    company_id: int | None = None
    initiatives: list[dict[str, Any]] | None = None


class RiskDashboardOut(BaseModel):
    distributions: dict[str, Any] | None = None
    cfar_var: dict[str, Any] | None = None
    distress: dict[str, Any] | None = None
    plan_attainment: dict[str, Any] | None = None
    heat_map: list[dict[str, Any]] | None = None
    risk_grade: dict[str, Any] | None = None
    narrative: list[str] | None = None
    checkpoints: list[dict[str, Any]] | None = None
    all_checkpoints_pass: bool | None = None


class OptimizeOut(BaseModel):
    model: str | None = None
    calibration: dict[str, Any] | None = None
    horizon: int | None = None
    terminal_growth: float | None = None
    equity_value_optimal: float | None = None
    equity_value_status_quo: float | None = None
    optimization_uplift: float | None = None
    uplift_derivation: dict[str, Any] | None = None
    uplift_pct: float | None = None
    recommended_plan: list[dict[str, Any]] | None = None
    policy_slice_at_d0: list[dict[str, Any]] | None = None
    narrative: list[str] | None = None
    checkpoints: list[dict[str, Any]] | None = None
    all_checkpoints_pass: bool | None = None


class ObjectivesOut(BaseModel):
    company_id: int | None = None
    dataset_id: int | None = None
    uploaded_at: str | None = None
    filename: Any | None = None
    has_data: bool | None = None
    count: int | None = None
    legacy: bool | None = None
    objectives: list[dict[str, Any]] | None = None
    objectives_by_horizon: dict[str, Any] | None = None


class UrgentItemsOut(BaseModel):
    company_id: int | None = None
    generated_at: str | None = None
    intervention: list[dict[str, Any]] | None = None
    recognition: list[dict[str, Any]] | None = None
    counts: dict[str, Any] | None = None
    all_clear: bool | None = None
    thresholds: dict[str, Any] | None = None


class ExecutiveBriefOut(BaseModel):
    company: str | None = None
    as_of_year: int | None = None
    sections: list[dict[str, Any]] | None = None
    summary: list[str] | None = None
    checkpoints: list[dict[str, Any]] | None = None
    all_checkpoints_pass: bool | None = None


class IntelligenceHealthOut(BaseModel):
    health_index: float | None = None
    version: str | None = None
    detail: dict[str, Any] | None = None
    wacc_curve: list[dict[str, Any]] | None = None


class DatasetProfileOut(BaseModel):
    dataset_id: int | None = None
    name: str | None = None
    source: str | None = None
    company: dict[str, Any] | None = None
    logo_url: str | None = None
    coverage: dict[str, Any] | None = None
    lineage_depth: int | None = None
    root_is_self: bool | None = None
    documents_attached: int | None = None
    latest_valuation: dict[str, Any] | None = None
    created_at: str | None = None


class AssessmentSwotOut(BaseModel):
    has_data: bool | None = None
    cycle_id: int | None = None
    revision: int | None = None
    closed_at: str | None = None
    prior_cycle_id: int | None = None
    sentiment_available: bool | None = None
    sliced: bool | None = None
    slice: Any | None = None
    counts: dict[str, Any] | None = None
    strengths: list[dict[str, Any]] | None = None
    weaknesses: list[dict[str, Any]] | None = None
    opportunities: list[dict[str, Any]] | None = None
    threats: list[Any] | None = None
    watch_list: list[dict[str, Any]] | None = None


class ScenarioLeversOut(BaseModel):
    revenue_growth: dict[str, Any] | None = None
    ebit_margin: dict[str, Any] | None = None
    leverage: dict[str, Any] | None = None
    capex_intensity: dict[str, Any] | None = None
    cost_shock: dict[str, Any] | None = None


class TwinLineageOut(BaseModel):
    root_dataset_id: int | None = None
    versions: list[dict[str, Any]] | None = None
    syncs_completed: int | None = None


class TwinSimulateOut(BaseModel):
    scenario: str | None = None
    shifts: dict[str, Any] | None = None
    seed: int | None = None
    n_paths: int | None = None
    drivers_used: dict[str, Any] | None = None
    financing_assumption: str | None = None
    years: list[int] | None = None
    revenue_fan: list[dict[str, Any]] | None = None
    fcff_fan: list[dict[str, Any]] | None = None
    cash_fan: list[dict[str, Any]] | None = None
    p_negative_fcff_by_year: list[float] | None = None
    p_cash_below_zero_ever: float | None = None
    sample_paths: dict[str, Any] | None = None
    sample_paths_note: str | None = None
    ergodicity: dict[str, Any] | None = None
    checkpoints: list[dict[str, Any]] | None = None
    all_checkpoints_pass: bool | None = None


class RealOptionsSuiteOut(BaseModel):
    subject: str | None = None
    underlying_enterprise_value: float | None = None
    options: dict[str, Any] | None = None
    total_flexibility_value: float | None = None
    note: str | None = None
    all_checkpoints_pass: bool | None = None


class ValuationMultiplesOut(BaseModel):
    subject: str | None = None
    ebitda: float | None = None
    ebit: float | None = None
    bridge_to_equity: float | None = None
    net_debt: float | None = None
    preferred_equity: float | None = None
    minority_interest: float | None = None
    dlom: float | None = None
    trailing_year: int | None = None
    sector: str | None = None
    methods: list[dict[str, Any]] | None = None
    implied_ev_range: dict[str, Any] | None = None
    intrinsic_dcf_ev: float | None = None
    narrative: list[str] | None = None
    checkpoints: list[dict[str, Any]] | None = None
    all_checkpoints_pass: bool | None = None


class BenchmarksCompareOut(BaseModel):
    company: str | None = None
    sector: str | None = None
    as_of_year: int | None = None
    currency: str | None = None
    source: dict[str, Any] | None = None
    benchmark_performance_index: float | None = None
    verdict: str | None = None
    rag_rule: dict[str, Any] | None = None
    kpis: list[dict[str, Any]] | None = None
    narrative: list[str] | None = None
    checkpoints: list[dict[str, Any]] | None = None
    all_checkpoints_pass: bool | None = None
