"""B16 item 6 — WIRING. ⭐ Built is not wired, and a passing suite cannot tell.

⭐ THE INSTANCE THIS TEST EXISTS FOR. `assumptions_api.py` shipped at `1ba395c`,
was mounted in `main.py`, and passed twenty-one tests — and MEASURED AT `2388e34`
THE FRONTEND CONTAINED ZERO REFERENCES TO IT. A live paying customer holding
`size_premium = 0.2` still could not correct it. Every existing test asserted the
server side, and none could see that nothing called it.

⭐ SO THE ASSERTION CROSSES THE REPO BOUNDARY. It reads the paths the UI actually
calls out of the frontend source and requires each to exist in the app's OWN
OpenAPI schema — both sides DERIVED, neither a hand list. A hand list on either
side is how the two drift while both look green.

⭐⭐ WHAT THIS TEST CANNOT SEE, STATED SO IT IS NOT MISTAKEN FOR PROOF. It proves
the UI calls a path the server serves. It does NOT prove the route is registered
in `routeTree.gen.ts` — that file is generated by the TanStack plugin and could
not be regenerated in the build environment (no JS runtime present). Until it is,
the page is unreachable in the browser. **That remainder is real and is recorded
in CORE, not papered over here.**
"""
import os
import re
import tempfile

os.environ.setdefault("DATABASE_URL", "sqlite:///" + tempfile.mktemp(suffix=".db"))

import pytest
from fastapi.testclient import TestClient

FRONTEND = "/Users/samirasaf/dev/optimization-anchor"
UI_FILE = os.path.join(FRONTEND, "src/routes/assumptions.tsx")


@pytest.fixture(scope="module")
def served_paths():
    """Every path the app actually serves, from its own schema."""
    from services.api.main import app
    with TestClient(app) as c:
        return set(c.get("/openapi.json").json()["paths"])


def _ui_source():
    if not os.path.exists(UI_FILE):
        pytest.skip("frontend checkout not present")
    return open(UI_FILE, encoding="utf-8").read()


def _ui_called_paths(src):
    """⭐ DERIVED FROM THE UI SOURCE, not listed here. Template literals like
    `/companies/${companyId}/assumptions` are normalised to the OpenAPI form."""
    out = set()
    for raw in re.findall(r"api<[^>]*>\(\s*`([^`]+)`", src) + \
               re.findall(r"api\(\s*`([^`]+)`", src):
        out.add(re.sub(r"\$\{[^}]+\}", "{company_id}", raw))
    return out


def test_the_ui_calls_at_least_one_assumptions_endpoint():
    """⭐ THE GUARD'S OWN KNOWN POSITIVE. A wiring test that found no calls would
    pass vacuously — which is exactly the state it was written to detect."""
    called = _ui_called_paths(_ui_source())
    assert called, "the UI file calls no API path at all"
    assert any("assumptions" in p for p in called), \
        "the assumptions page calls no assumptions endpoint"


def test_every_path_the_UI_calls_is_actually_SERVED(served_paths):
    """⭐ BOTH SIDES DERIVED. A UI calling a path the server does not serve is a
    404 the suite would otherwise never see."""
    called = _ui_called_paths(_ui_source())
    missing = sorted(p for p in called if p not in served_paths)
    assert not missing, (
        f"the UI calls paths the app does not serve: {missing}. "
        f"Nearest served: {sorted(p for p in served_paths if 'assumption' in p)}")


def test_the_read_and_write_and_history_endpoints_are_all_reachable(served_paths):
    base = "/companies/{company_id}/assumptions"
    assert base in served_paths
    assert base + "/history" in served_paths


def test_the_write_endpoint_is_a_PATCH_and_the_reads_are_GETs():
    from services.api.main import app
    with TestClient(app) as c:
        spec = c.get("/openapi.json").json()["paths"]
    base = "/companies/{company_id}/assumptions"
    assert "patch" in spec[base], "no write method on the assumptions endpoint"
    assert "get" in spec[base]
    assert "get" in spec[base + "/history"]


def test_the_UI_does_not_reimplement_the_bounds_as_a_CLIENT_SIDE_BLOCK():
    """⭐⭐ FLAG, NEVER REFUSE — AND THE CLIENT MUST NOT UNDO IT. A client that
    refuses what the server stores is a second, stricter rule nobody audits, and
    it would lock the customer out exactly as a refusing server would. 0.2 is
    implausible, not impossible."""
    src = _ui_source()
    # no min/max attributes on the numeric inputs, and no pre-submit rejection
    assert not re.search(r"<input[^>]*\bmin=", src), \
        "the UI constrains a field with min= — the server flags, it does not refuse"
    assert not re.search(r"<input[^>]*\bmax=", src), \
        "the UI constrains a field with max= — the server flags, it does not refuse"
    for banned in ("out of range", "must be between", "invalid value"):
        assert banned not in src.lower(), \
            f"the UI refuses a value client-side ({banned!r})"


def test_the_UI_renders_the_warning_AND_says_the_value_was_stored():
    """⭐ A warning that does not also confirm storage reads as a rejection."""
    src = _ui_source()
    assert "warnings" in src, "the UI ignores the server's bounds warnings"
    assert "stored as entered" in src.lower(), \
        "the UI shows a warning without confirming the value was stored"


def test_the_UI_offers_NO_BUTTON_that_acts_on_the_invalidation_options():
    """⭐⭐ STATED, NOT CHOSEN. Recompute / mark-stale / badge has not been ruled;
    a UI button would choose it silently."""
    src = _ui_source()
    assert "invalidation" in src, "the UI hides what an edit invalidates"
    # the options are displayed…
    assert "options.join" in src or "options" in src
    # …and nothing acts on them
    for act in ("recompute()", "onRecompute", "markStale", "handleRecompute"):
        assert act not in src, f"the UI acts on an unruled option ({act})"


def test_the_UI_states_that_a_PUBLISHED_PACK_CANNOT_MOVE():
    """⭐ The freeze is the one non-optional part of invalidation."""
    src = _ui_source().lower()
    assert "published pack" in src
    assert "frozen" in src


def test_absence_propagates_in_the_UI_an_empty_box_is_NOT_zero():
    """⭐ A first-time entry and a change from zero are different events, and the
    server stores them apart via prior_absent."""
    src = _ui_source()
    assert "return null" in src, "toNum does not propagate absence"
    assert re.search(r'if \(t === ""\) return null', src), \
        "an empty input does not resolve to null"
